# Generated by Django 4.0.3 on 2022-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maincategory',
            table='main_categories',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
